version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer  
      - MSSQL_SA_PASSWORD=AgroConecta25
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - db-network

volumes:
  sql-data:

networks:
  db-network:
    driver: bridge